# Choice of model name, determines the chosen interface and is printed in the output table
interface: CMIP6_PD
model:
   name: EC-Earth3

dirs:
   exp: /archive/paolo/cmip6
   tab: /work/scratch/users/paolo/ecmean_cmip6
   clm: /home/paolo/ECmean4/climatology

global:
  atm_vars: [tas]
  oce_vars: []
  tab_vars: [tas]


PI:
  2d_vars:
    field: [net_sfc, tas, psl, pr, tauu, tauv]
  3d_vars:
    field: [ta, ua, va, hus]
  oce_vars:
    field: [tos, sos]
  ice_vars:
    field: [siconc]
  resolution: r180x91

