dirs:
   exp: /lus/h2resw01/scratch/ccpd/ece4 
   tmp: /ec/res4/scratch/ccjh/ece4
   tab: /ec/res4/scratch/ccjh/ece4
   clm: /home/ccpd/perm/ecearth4/ECmean4/climatology

global:
  atm_vars:
    field: [tas, psl, pr, evspsbl, pme, clt, cll, clm, clh]
    radiation: [rsnt, rlnt, rsns, rlns, hfss, hfls, rsntcs, rlntcs, net_toa, net_sfc_nosn, toamsfc_nosn, net_sfc, toamsfc]
  tab_vars: [rsnt, rlnt, net_toa, rsns, rlns, hfss, hfls, swcf, lwcf, net_sfc, toamsfc, tas, clt, cll, clm, clh, pr, pme, psl]


PI: 
  2d_vars:
    field: [tas, psl, pr, tauu, tauv]
  3d_vars: 
    field: [ua]
