dirs:
   exp: /lus/h2resw01/scratch/ccpd/ece4 
   tmp: /ec/res4/scratch/ccjh/ece4/ECmean4/table/
   tab: /ec/res4/scratch/ccjh/ece4/ECmean4/table/
   clm: /home/ccpd/perm/ecearth4/ECmean4/climatology

global:
  atm_vars:
    field: [tas, psl, pr, evspsbl, pme, clt, cll, clm, clh, pr_oce, pme_oce, pr_land, pme_land]
    radiation: [net_toa, rsnt, rlnt, rsntcs, rlntcs, swcf, lwcf, rsns, rlns, hfss, hfls, net_sfc_nosn, net_sfc, toamsfc_nosn, toamsfc]
  tab_vars: [rsnt, rlnt, net_toa, rsns, rlns, hfss, hfls, swcf, lwcf, net_sfc, toamsfc, tas, clt, cll, clm, clh, pr, pme, psl]

PI: 
  2d_vars:
    field: [tas, psl, pr, tauu, tauv]
  3d_vars: 
    field: [ta, ua, va, hus]
