# Choice of model name, determines the chosen interface and is printed in the output table
interface: GLOBO
model:
   name: GLOBONE

dirs:
   exp: /ec/res4/scratch/ccff/globone
   tab: /lus/h2resw01/scratch/ccpd/globo
   clm: /perm/ccpd/ecearth4/ECmean4

global:
  atm_vars: [tas, psl, pr, evspsbl, pme, clt,
             pr_oce, pme_oce, pr_land, pme_land,
             net_toa, rsnt, rlnt, 
             rsns, rlns, hfss, hfls, net_sfc_nosn, net_sfc,
             toamsfc_nosn, toamsfc]
  oce_vars: []
  tab_vars: [rsnt, rlnt, net_toa, rsns, rlns, hfss, hfls, net_sfc, toamsfc, tas, clt, pr, pme, psl]


PI:
  2d_vars:
    field: [net_sfc, tas, psl, pr]
  3d_vars:
    field: [ta, ua, va, hus]
  oce_vars:
    field: [tos, sos]
  ice_vars:
    field: [siconc]
  resolution: r180x91
