# Create the ECmean4 development environment:
# mamba env create -f dev-environment.yml 
# or 
# conda env create -f dev-environment.yml

name : ecmean
channels:
  - conda-forge
dependencies:
  - python=>3.8
  - libnetcdf
  - xesmf<0.8
  - eccodes
  - esmpy
  - cdo
  - ncview
  - ipykernel
  - flake8
  - autopep8
  - pip
  - pip:
    - -e .[all]

