# For developers only:
# Create the ECmean4 environment:
#   conda env create -f dev_environment.yml

name : ECmean4
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9 
  - numpy
  - netcdf4 
  - dask
  - xarray
  - xesmf
  - metpy
  - tabulate
  - cfgrib
  - pytest
  - flake8
  - autopep8
  - sphinx
  - sphinx_rtd_theme
  - ipykernel
