# For developers only:
# Create the ECmean4 environment:
#   conda env create -f dev_environment.yml

name : ECmean4
channels:
  - conda-forge
dependencies:
  - python>=3.8,<3.11
  - numpy
  - netcdf4 
  - dask
  - xarray
  - cfgrib
  - xesmf
  - esmpy=8.3.1 #temporary
  - matplotlib-base>=3.5.0
  - metpy
  - seaborn
  - tabulate
  - pytest
  - flake8
  - autopep8
  - sphinx
  - sphinx_rtd_theme
  - ipykernel
