# Create the ECmean4 environment:
# mamba env create -f environment.yml 
# or 
# conda env create -f environment.yml

name : ECmean4
channels:
  - conda-forge
dependencies:
  - python>=3.8,<3.11
  - netcdf4 
  - dask
  - xarray
  - xesmf
  - esmpy<=8.3.1
  - metpy
  - tabulate
  - cfgrib
  - seaborn
  - pytest
  - coverage
