# Create the ECmean4 environment:
# mamba env create -f environment.yml 
# or 
# conda env create -f environment.yml

name : ECmean4
channels:
  - conda-forge
  - numba
dependencies:
  - python>=3.8
  - netcdf4 
  - dask
  - xarray
  - xesmf
  - numba
  - esmpy
  - metpy
  - tabulate
  - cfgrib
  - seaborn
  - pytest
  - coverage
  - pip
  - pip:
    - sparse
