# Create the ECmean4 environment:
#   conda env create -f environment.yml

name : ECmean4
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9 
  - numpy
  - netcdf4 
  - dask
  - xarray
  - xesmf
  - esmpy=8.3.1 #temporary
  - matplotlib>3.5
  - metpy
  - tabulate
  - cfgrib
  - seaborn
