# Create the ECmean4 environment:
#   conda env create -f environment.yml

name : ECmean4
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - numpy
  - netcdf4 
  - dask
  - xarray
  - xesmf
  - esmpy=8.3.1 #temporary
  - matplotlib-base=3.6.2
  - metpy
  - tabulate
  - cfgrib
  - seaborn
