# Create the ECmean4 environment:
# mamba env create -f environment.yml 
# or 
# conda env create -f environment.yml

name : ecmean
channels:
  - conda-forge
dependencies:
  - python=>3.8
  - libnetcdf
  - xesmf
  - esmpy
  - pip
  - pip:
    - -e .[all]

