# Create the ECmean4 environment:
#   conda env create -f environment.yml

name : ECmean-311
channels:
  - conda-forge
dependencies:
  - python>=3.8,<3.11
  - numpy
  - netcdf4 
  - dask
  - xarray
  - xesmf
  - esmpy<=8.3.1
  - matplotlib-base
  - metpy<=1.3.1
  - tabulate
  - numba
  - cfgrib
  - seaborn
  - pytest
