# Choice of model name, determines the chosen interface and is printed in the output table
# Configuration file for benchmarking, please not change. To be run on Wilma. 
interface: CMIP6_PD
model:
   name: EC-Earth3

dirs:
   exp: /archive/paolo/cmip6
   tab: /work/scratch/users/paolo/ecmean_cmip6
   clm: /home/paolo/ECmean4/climatology
   fig: /work/users/paolo/figures/ECmean4

global:
  atm_vars: [tas, psl, pr, evspsbl, pme, clt, cll, clm, clh,
             pr_oce, pme_oce, pr_land, pme_land,
             net_toa, rsnt, rlnt, rsntcs, rlntcs, swcf, lwcf,
             rsns, rlns, hfss, hfls, net_sfc_nosn, net_sfc,
             toamsfc_nosn, toamsfc]
  oce_vars: [tos, sos, zos, wfo]
  ice_vars: [siconc_north, siconc_south]
  tab_vars: [rsnt, rlnt, net_toa, rsns, rlns, hfss, hfls, swcf, lwcf, net_sfc, toamsfc,
             tas, clt, cll, clm, clh, pr, pme, psl]

PI:
  2d_vars:
    field: [net_sfc, tas, psl, pr, tauu, tauv]
  3d_vars:
    field: [ta, ua, va, hus]
  oce_vars:
    field: [tos, sos]
  ice_vars:
    field: [siconc]
  regions: ['Global', 'North Midlat', 'Tropical', 'South Midlat']
  seasons: ['ALL', 'DJF', 'JJA']
  resolution: r360x180
