# For developers only:
# Create the ECmean4 environment:
#   conda env create -f environment.yml

name : ECmean4
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9 
  - numpy
  - netcdf4 
  - dask
  - xarray
  - xesmf
  - metpy
  - tabulate
  - cfgrib
  - seaborn
